from wngPdlsDB.document.playlist_document import PlaylistDocument
from wngPdlsDB.document.tag_document import TagDocument
from wngPdlsDB.document.song_document import SongDocument
from wngPdlsDB.document.artist_document import ArtistDocument
from wngPdlsDB.document.album_document import AlbumDocument
