name: run test

on: 
  pull_request: 
    branches: [main]
  push:
    branches: [main]
jobs: 
  test: 
    name: run test
    runs-on: ubuntu-latest 

    steps: 
    - uses: actions/checkout@v3 

    - name: setup python 
      uses: actions/setup-python@v4 
      with: 
        python-version: '3.10'

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-seq-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: install dependencies 
      run: pip install -r dev-requirements.txt

    - name: pytest
      run: pytest
